#!/bin/sh
# Copyright (C) 2006-2010 OpenWrt.org
# Copyright (C) 2010 Vertical Communications

find_mount_jffs2() {
    echo "--- find_mount_jffs2 ---"
    mkdir -p /tmp/overlay
    mount "$(find_mtd_part rootfs_data)" /tmp/overlay -t jffs2
    mtd -qq unlock rootfs_data
}

jffs2_not_mounted() {
    echo "--- jffs2_not_mountd ---"
    if [ "$pi_jffs2_mount_success" != "true" ]; then
	return 0
    else
	return 1
    fi
}

do_mount_jffs2() {
    echo ">>> 40) do_mount_jffs2 ---"
    check_skip || {
	find_mount_jffs2 && pi_jffs2_mount_success=true
    }
    echo "<<< 40) do_mount_jffs2 ---"
}

# boot_hook_add preinit_mount_root do_mount_jffs2

