#!/bin/sh

case "$1" in
	start)
		if ! pidof syslogd | sed "s/$$\$//" | grep -q [0-9]
		then
			syslogd -f /etc/config/syslogd.conf
			klogd -c 1
		fi  
		;;  

	stop)
		pkill klogd 2>/dev/null
		pkill syslogd 2>/dev/null
		;;  


	restart)
		"$0"    stop
		"$0"    start
		;;  

	status)
		if pidof syslogd | sed "s/$$\$//" | grep -q [0-9] ; then
			if pidof klogd >/dev/null ; then
				echo "running"
			else
				echo "stopped"
			fi  
		else
			echo "stopped"
		fi  
		;;  

	*)  
		echo $"Usage: $0 {start|stop|restart|status}"
		exit 1
esac  
