/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef FTM50S_H
#define FTM50S_H

/* function declarations */
void init_ftm50s(void);
FindVarMethod var_ftm50s;
FindVarMethod var_tempTable;
FindVarMethod var_humiTable;
FindVarMethod var_diTable;
FindVarMethod var_doTable;
FindVarMethod var_rlTable;
    WriteMethod write_prodDescription;
    WriteMethod write_tempName;
    WriteMethod write_tempState;
    WriteMethod write_tempUpdateInterval;
    WriteMethod write_humiName;
    WriteMethod write_humiState;
    WriteMethod write_humiUpdateInterval;
    WriteMethod write_diName;
    WriteMethod write_diState;
    WriteMethod write_diUpdateInterval;
    WriteMethod write_doName;
    WriteMethod write_doState;
    WriteMethod write_doUpdateInterval;
    WriteMethod write_rlName;
    WriteMethod write_rlState;
    WriteMethod write_rlUpdateInterval;

#endif /* FTM50S_H */
