#!/bin/sh

. /lib/functions/ftmenv.sh

TASK="node"
#OPTIONS="--stack_size=1024 --max_old_space_size=20 --max_new_space_size=4096 --max_executable_size=10 --gc_global --gc_interval=100 --trace-gc --track_gc_object_stats --trace_gc_verbose"
OPTIONS="--stack_size=1024 --max_old_space_size=20 --max_new_space_size=4096 --max_executable_size=10"
DIR="/opt/thingplus-gateway/device"
LOG_DIR="/mnt/mtd/log"
RSYNC_FILE="$DIR/update/ftm-50/rsync.sh"

if [ -f $DIR/app.js ] ;  then
CMD="$TASK $OPTIONS app.js"
else 
CMD="$TASK $OPTIONS app.min.js"
fi

case "$1" in
	status)
		if pidof $TASK | sed "s/$$\$//" | grep -q [0-9] ; then
			echo "running"
		else
			echo "stopped"
		fi
		;;

	start) 
    #recover rsync if needed
    $RSYNC_FILE -r

		if ! pidof $TASK | sed "s/$$\$//" | grep -q [0-9] ; then
			cd $DIR
		#	$CMD 2>&1 | svlogd $LOG_DIR &
			$CMD  | svlogd $LOG_DIR &
		fi	
		;;

	stop) 
		pkill $TASK 2> /dev/null &
		;;

	restart)
		"$0"	stop
		"$0"	start
		;;

	*)
		echo $"Usage: $0 {start|stop|restart}"
		exit 1
esac
