/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef FTM50S_H
#define FTM50S_H

/* function declarations */
void init_ftm50s(void);
FindVarMethod var_ftm50s;
FindVarMethod var_netTable;
FindVarMethod var_pointTable;
FindVarMethod var_sensorTable;
    WriteMethod write_prodDescription;
    WriteMethod write_netIP;
    WriteMethod write_sensorName;
    WriteMethod write_sensorState;
    WriteMethod write_sensorUpdateInterval;

#endif /* FTM50S_H */
