/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef FUTURETEK_H
#define FUTURETEK_H

/* function declarations */
void init_futuretek(void);
FindVarMethod var_futuretek;

#endif /* FUTURETEK_H */
