#!/bin/sh
# Copyright (C) 2006 OpenWrt.org
# Copyright (C) 2010 Vertical Communications

initramfs_test() {
    echo "--- initramfs_test ---"
    echo "--- 70) initramfs_test: INITRAMFS = $INITRAMFS"
    if [ -n "$INITRAMFS" ]; then
        echo "--- 70) initramfs_test: boot_run_hook initramfs "
	boot_run_hook initramfs
	preinit_ip_deconfig
	break
    fi
}

# boot_hook_add preinit_main initramfs_test

