#!/bin/sh
# Copyright (C) 2006 OpenWrt.org
# Copyright (C) 2010 Vertical Communications

run_init() {
    preinit_echo "- init -"
    preinit_echo "1) 99_10_run_init"
    preinit_ip_deconfig
    # preinit_echo "1.1) 99_10_run_init"
    # mount -o remount,rw /
    preinit_echo "2) 99_10_run_init"
    preinit_echo "pi_init_path: $pi_init_path"
    preinit_echo "pi_init_env: $pi_init_env"
    preinit_echo "pi_init_cmd: $pi_init_cmd"
    if [ "$pi_init_suppress_stderr" = "y" ]; then
    	preinit_echo "3) 99_10_run_init"
    	preinit_echo "============="
	exec env - PATH=$pi_init_path $pi_init_env $pi_init_cmd 2>&0
    else
    	preinit_echo "4) 99_10_run_init"
    	preinit_echo "============="
	exec env - PATH=$pi_init_path $pi_init_env $pi_init_cmd
    fi
}

# boot_hook_add preinit_main run_init

