#!/bin/sh

. /lib/functions/ftmenv.sh

WAN=$(get_wan)
BRIDGE_MODE=$(is_bridge)

case "$1" in
	start)
		if [ "$BRIDGE_MODE" = "on" ]
		then
			brctl addbr lan
			if [ "$WAN" = "ppp0" ]
			then
				brctl addif lan eth0
			fi
			brctl addif lan eth1
		fi
		;;

	stop)
		if [ "$BRIDGE_MODE" = "on" ]
		then
			brctl delif lan eth1
			if [ "$WAN" = "ppp0" ]
			then
				brctl delif lan eth0
			fi
			brctl delbr lan
		fi
		;;

	restart)
		"$0" stop
		"$0" start
		;;
esac

