#!/bin/sh
# Start/stop the cron daemon.

test -f /usr/sbin/cron || exit 0

LSBNAMES='-l'  # Uncomment for LSB name support in /etc/cron.d/

case "$1" in
	start)	
		start-stop-daemon --start --quiet --pidfile /var/run/crond.pid \
			--name cron --startas /usr/sbin/cron -- $LSBNAMES
		;;

	stop)	
		start-stop-daemon --stop --quiet --pidfile /var/run/crond.pid --name cron
        ;;

	restart) 
		start-stop-daemon --stop --retry 5 --quiet --pidfile /var/run/crond.pid --name cron
        start-stop-daemon --start --quiet --pidfile /var/run/crond.pid \
			--name cron --startas /usr/sbin/cron -- $LSBNAMES
        ;;

	reload|force-reload) 
		# cron reloads automatically
        ;;

	*)	
		echo "Usage: /etc/init.d/cron start|stop|restart|reload|force-reload"
        exit 1 
        ;;
esac

exit 0
