#!/bin/sh

sys_init()
{
	if [ ! -e /etc/initialized ]
	then
		echo 'done' > /etc/initialized
		echo "System initialize completed."
		echo "Reboot now ..."
		reboot -d 2
		sleep 2
	fi
}

case "$1" in
	start) sys_init;;
esac
