#!/bin/sh

tpgw_init()
{
	if [ -e /opt/thingplus-gateway ]
	then
		echo "/opt/thingplus-gateway exists."
		if [ ! -e /mnt/mtd/log ]
		then
			mkdir /mnt/mtd/log
			cp /opt/thingplus-gateway/config /mnt/mtd/log
		fi
	else
		echo "/opt/thingplus-gateway not exists."
	fi	

	if [ ! -e /etc/initialized ]
	then
		echo 'done' > /etc/initialized
		echo "System initialize completed."
		echo "Reboot now ..."
		reboot -d 2
		sleep 2
	fi
}

case "$1" in
	start) tpgw_init;;
esac
