#!/bin/sh
#
# mount mini_fo overlay file system and execute init
#
#   ---------------------------------------------
#   Prints execution status.
#
#   arg1 : Execution status
#   arg2 : Continue (0) or Abort (1) on error
#   ---------------------------------------------
status ()
{
       if [ $1 -eq 0 ] ; then
               echo "[SUCCESS]"
       else
               echo "[FAILED]"

               if [ $2 -eq 1 ] ; then
                       echo "... System init aborted."
                       exit 1
               fi
       fi

}

echo -n " Mounting /proc             : "
mount -n -t proc /proc /proc
status $? 1
 
echo -n " Mounting /sys              : "
mount -n -t sysfs sysfs /sys
status $? 1

echo -n " Mounting /dev              : "
mount -n -t tmpfs mdev /dev
status $? 1

echo -n " Mounting /tmp              : "
mount -n -t tmpfs tmpfs /tmp
status $? 1

echo -n " Mounting /dev/pts          : "
mkdir /dev/pts
mount -n -t devpts devpts /dev/pts
status $? 1

echo -n " Enabling hot-plug          : "
echo "/sbin/mdev" > /proc/sys/kernel/hotplug
status $? 0

echo -n " Mounting /proc/bus/usb     : "
mount -n -t usbfs usbfs /proc/bus/usb
status $? 1

echo -n " Populating /dev            : "
mkdir /dev/input
mkdir /dev/snd
mkdir /dev/net

mdev -s
status $? 0

echo -n " Mounting /tmp/overlay      : "
mkdir -p /tmp/overlay
mount -n -t yaffs2 /dev/mtdblock7 /tmp/overlay
status $? 1

mount -o move /tmp/overlay /overlay

mount -n -t overlayfs -o noatime,lowerdir=/,upperdir=/overlay 'overlayfs:/overlay' /mnt 1>& /dev/null
echo -n " Mounting overlayfs:/overlay: "
status $? 1

mount -o move /proc /mnt/proc

pivot_root /mnt /mnt/rom

mount -o move /rom/sys	/sys
mount -o move /rom/dev	/dev
mount -o move /rom/tmp	/tmp
mount -o move /rom/overlay /overlay

echo -n " Mounting /var/run          : "
mount -n -t tmpfs tmpfs /var/run
status $? 1

echo -n " Mounting /var/lock         : "
mount -n -t tmpfs tmpfs /var/lock
status $? 1

echo -n " Mounting /var/lib          : "
mount -n -t tmpfs tmpfs /var/lib
status $? 1

echo -n " Mounting /var/log          : "
mount -n -t tmpfs tmpfs /var/log
status $? 1

echo -n " Mounting /var/empty        : "
mount -n -t tmpfs tmpfs /var/empty
status $? 1


#if [ ! -e /etc ]
#then
#	mkdir /etc
#	cp -rf /etc.default/* /etc
#	echo "System initialized."
#fi
#
#if [ ! -e /opt/thingplus-gateway ]
#then
#	cd /
#	tar xvfz /opt/tpgw.tgz 
#	echo "ThingPlus-Gateway installation completed."
#fi

exec /sbin/init

