#!/bin/sh
#
# mount mini_fo overlay file system and execute init
#
#   ---------------------------------------------
#   Prints execution status.
#
#   arg1 : Execution status
#   arg2 : Continue (0) or Abort (1) on error
#   ---------------------------------------------
status ()
{
       if [ $1 -eq 0 ] ; then
               echo "[SUCCESS]"
       else
               echo "[FAILED]"

               if [ $2 -eq 1 ] ; then
                       echo "... System init aborted."
                       exit 1
               fi
       fi

}

echo -n " Mounting /proc             : "
mount -n -t proc /proc /proc
status $? 1
 
echo -n " Mounting /sys              : "
mount -n -t sysfs sysfs /sys
status $? 1

echo -n " Mounting /dev              : "
mount -n -t tmpfs mdev /dev
status $? 1

echo -n " Mounting /tmp              : "
mount -n -t tmpfs tmpfs /tmp
status $? 1

echo -n " Mounting /dev/pts          : "
mkdir /dev/pts
mount -n -t devpts devpts /dev/pts
status $? 1

echo -n " Enabling hot-plug          : "
echo "/sbin/mdev" > /proc/sys/kernel/hotplug
status $? 0

echo -n " Mounting /proc/bus/usb     : "
mount -n -t usbfs usbfs /proc/bus/usb
status $? 1

echo -n " Populating /dev            : "
mkdir /dev/input
mkdir /dev/snd
mkdir /dev/net

mdev -s
status $? 0

mkdir -p /tmp/overlay
mount -n -t yaffs2 /dev/mtdblock7 /tmp/overlay
echo -n " Mounting /tmp/overlay      : "
status $? 1

mount -o move /tmp/overlay /overlay

mount -n -t overlayfs -o noatime,lowerdir=/,upperdir=/overlay 'overlayfs:/overlay' /mnt 2>&1
echo -n " Mounting overlayfs:/overlay: "
status $? 1

mount -o move /proc /mnt/proc

pivot_root /mnt /mnt/rom

mount -o move /rom/sys	/sys
mount -o move /rom/dev	/dev
mount -o move /rom/tmp	/tmp
mount -o move /rom/overlay /overlay

echo -n " Mounting /var              : "
mount -n -t tmpfs tmpfs /var
status $? 1

mkdir -p /var/run
mkdir -p /var/lock
mkdir -p /var/log
mkdir -p /var/empty
mkdir -p /var/lib/misc
mkdir -p /var/spool/cron/crontabs

cat /proc/filesystems | grep -q debugfs
if [ $? -eq 0 ]
then
	echo -n " Mounting debugfs           : "
	mkdir /dev/debug
	mount -n -t debugfs debugfs /sys/kernel
	status $? 1
fi

exec /sbin/init

